const allClientList = [
  {
    id: 41,
    type: "PDA",
    name: "TEST_PDA",
    description: "",
  },
  {
    id: 42,
    type: "PDA",
    name: "TEST_PDA2",
    description: "",
  },
];

const luAgentList = [
  {
    listNo: 1,
    name: "GLU103",
    commSetting: {
      scl_file_path: "NCGLU_v_1_5_230629_GLU103_for_YH.cid",
      ied_name: "NC",
      ied_manufacturer: "NC",
      server_61850_ip: "192.168.10.54",
      server_61850_port: "102",
      osi_ap_title: "1,1,9999,1",
      osi_ae_qualifier: "1",
      osi_psel: "00000001",
      osi_ssel: "0001",
      osi_tsel: "0001",
      pdu_size: "32000",
      auto_start: "1",
      use_indexed_rcb: "0",
      Report_auto_enable: "1",
      Report_to_MQTT: "0",
      Report_to_DUServer: "1",
      MoDevFlt_TrueIsNormal: "0",
      UseChannelZeroIndex: "1",
      setpoint_priority: "DUSERVER",
      lu_type: "glu",
    },
    status: "on",
    process: {
      cpu: 0.07936507936507936,
      memory: 117465088,
      ctime: 1493600,
      elapsed: 3347869540,
      timestamp: 1728612415156,
      pid: 8,
      ppid: 0,
    },
    listLD: [
      {
        name: "NCGLU",
        listLN: [
          "SPDC1",
          "SPDC2",
          "SPDC3",
          "SPDC4",
          "SPDC5",
          "SPDC6",
          "SPDC7",
          "SPDC8",
          "SPDC9",
          "SPDC10",
          "SPDC11",
          "SPDC12",
          "SPDC13",
          "SPDC14",
          "SPDC15",
          "SPDC16",
          "SPDC17",
          "SPDC18",
          "SPDC19",
          "SPDC20",
          "SPDC21",
          "SPDC22",
          "SPDC23",
          "SPDC24",
          "SPDC25",
          "SPDC26",
          "SPDC27",
          "SPDC28",
          "SPDC29",
          "SPDC30",
          "SPDC31",
          "SPDC32",
          "SCBR1",
          "SCBR2",
          "SCBR3",
        ],
      },
    ],
  },
  {
    listNo: 2,
    name: "TEST_PDA",
    commSetting: {
      scl_file_path: "YOUHO_DU.ICD",
      ied_name: "YH",
      ied_manufacturer: "YOUHO ELECTRIC",
      server_61850_ip: "10.92.64.233",
      server_61850_port: 102,
      osi_ap_title: "1,1,9999,1",
      osi_ae_qualifier: "1",
      osi_psel: "00000001",
      osi_ssel: "0001",
      osi_tsel: "0001",
      pdu_size: 0,
      auto_start: false,
      use_indexed_rcb: false,
      Report_auto_enable: "1",
      Report_to_MQTT: "1",
      Report_to_DUServer: "1",
      MoDevFlt_TrueIsNormal: "0",
      UseChannelZeroIndex: "1",
      setpoint_priority: "DUSERVER",
      lu_type: "PDA",
    },
    listLD: [
      {
        name: "YHLU01",
        ldNs: "GIS",
        listLN: [
          "SPDC1",
          "SPDC2",
          "SPDC3",
          "SPDC4",
          "SPDC5",
          "SPDC6",
          "SPDC7",
          "SPDC8",
          "SPDC9",
          "SPDC10",
          "SPDC11",
          "SPDC12",
          "SPDC13",
          "SPDC14",
          "SPDC15",
          "SPDC16",
          "SPDC17",
          "SPDC18",
          "SPDC19",
          "SPDC20",
          "SCBR1",
          "SCBR2",
          "SCBR3",
          "SCBR4",
          "SCBR5",
          "SCBR6",
          "SCBR7",
        ],
      },
      {
        name: "YHLU02",
        ldNs: "GIS",
        listLN: [
          "SPDC1",
          "SPDC2",
          "SPDC3",
          "SPDC4",
          "SPDC5",
          "SPDC6",
          "SPDC7",
          "SPDC8",
          "SPDC9",
          "SPDC10",
          "SPDC11",
          "SPDC12",
          "SPDC13",
          "SPDC14",
          "SPDC15",
          "SPDC16",
          "SPDC17",
          "SPDC18",
          "SPDC19",
          "SPDC20",
          "SPDC21",
          "SPDC22",
          "SPDC23",
          "SPDC24",
          "SCBR1",
          "SCBR2",
          "SCBR3",
          "SCBR4",
          "SCBR5",
          "SCBR6",
          "SCBR7",
          "SCBR8",
          "SCBR9",
        ],
      },
      {
        name: "YHLU03",
        ldNs: "MTR",
        listLN: [
          "SPDC1",
          "SPDC2",
          "SPDC3",
          "SPDC4",
          "SPDC5",
          "SPDC6",
          "SPDC7",
          "SPDC8",
          "SPDC9",
          "SPDC10",
          "SPDC11",
          "SPDC12",
          "SIML1",
          "SIML2",
          "SIML3",
          "SLTC1",
          "SBSH1",
          "SBSH2",
          "SBSH3",
          "SBSH4",
          "SBSH5",
          "SBSH6",
        ],
      },
      {
        name: "YHLU04",
        ldNs: "MTR",
        listLN: [
          "SPDC1",
          "SPDC2",
          "SPDC3",
          "SPDC4",
          "SIML1",
          "SLTC1",
          "SBSH1",
          "SBSH2",
          "SBSH3",
          "SBSH4",
          "SBSH5",
          "SBSH6",
        ],
      },
      {
        name: "YHLU05",
        ldNs: "MTR",
        listLN: [
          "SPDC1",
          "SPDC2",
          "SPDC3",
          "SPDC4",
          "SIML1",
          "SLTC1",
          "SBSH1",
          "SBSH2",
          "SBSH3",
          "SBSH4",
          "SBSH5",
          "SBSH6",
        ],
      },
      {
        name: "YHLU06",
        ldNs: "MTR",
        listLN: [
          "SIML1",
          "SIML2",
          "SIML3",
          "SLTC1",
          "SBSH1",
          "SBSH2",
          "SBSH3",
          "SBSH4",
          "SBSH5",
          "SBSH6",
        ],
      },
    ],
  },
  {
    listNo: 3,
    name: "TEST_PDA2",
    commSetting: {
      scl_file_path: "YOUHO_GMLU.ICD",
      ied_name: "YH",
      ied_manufacturer: "YOUHO ELECTRIC",
      server_61850_ip: "10.92.64.233",
      server_61850_port: 102,
      osi_ap_title: "1,1,9999,1",
      osi_ae_qualifier: "1",
      osi_psel: "00000001",
      osi_ssel: "0001",
      osi_tsel: "0001",
      pdu_size: 0,
      auto_start: false,
      use_indexed_rcb: false,
      Report_auto_enable: "1",
      Report_to_MQTT: "1",
      Report_to_DUServer: "1",
      MoDevFlt_TrueIsNormal: "0",
      UseChannelZeroIndex: "1",
      setpoint_priority: "DUSERVER",
      lu_type: "PDA",
    },
    listLD: [
      {
        name: "YHGLU",
        ldNs: "GIS",
        listLN: [
          "SPDC1",
          "SPDC2",
          "SPDC3",
          "SPDC4",
          "SPDC5",
          "SPDC6",
          "SPDC7",
          "SPDC8",
          "SPDC9",
          "SPDC10",
          "SPDC11",
          "SPDC12",
          "SPDC13",
          "SPDC14",
          "SPDC15",
          "SPDC16",
          "SPDC17",
          "SPDC18",
          "SPDC19",
          "SPDC20",
          "SPDC21",
          "SPDC22",
          "SPDC23",
          "SPDC24",
          "SPDC25",
          "SPDC26",
          "SPDC27",
          "SPDC28",
          "SPDC29",
          "SPDC30",
          "SPDC31",
          "SPDC32",
          "SCBR1",
          "SCBR2",
          "SCBR3",
          "SCBR4",
          "SCBR5",
          "SCBR6",
          "SCBR7",
          "SCBR8",
          "SCBR9",
          "SCBR10",
          "SCBR11",
          "SCBR12",
        ],
      },
      {
        name: "YHMLU",
        ldNs: "GIS",
        listLN: [
          "SPDC1",
          "SPDC2",
          "SPDC3",
          "SPDC4",
          "SPDC5",
          "SPDC6",
          "SPDC7",
          "SPDC8",
          "SPDC9",
          "SPDC10",
          "SPDC11",
          "SPDC12",
          "SPDC13",
          "SPDC14",
          "SPDC15",
          "SPDC16",
          "SIML1",
          "SIML2",
          "SIML3",
          "SIML4",
          "SIML5",
          "SIML6",
          "SIML7",
          "SIML8",
          "SIML9",
          "SIML10",
          "SIML11",
          "SIML12",
          "SIML13",
          "SIML14",
          "SLTC1",
          "SLTC2",
          "SLTC3",
          "SBSH1",
          "SBSH2",
          "SBSH3",
          "SBSH4",
          "SBSH5",
          "SBSH6",
          "SBSH7",
          "SBSH8",
          "SBSH9",
          "SBSH10",
          "SBSH11",
          "SBSH12",
        ],
      },
    ],
  },
];

// 중첩 속성을 최상위로 가져오기 위한 평탄화 함수
const flattenObject = (obj, prefix = "") => {
  if (!obj || typeof obj !== "object") return {}; // obj가 null, undefined이거나 객체가 아닐 경우 빈 객체 반환

  return Object.keys(obj).reduce((acc, k) => {
    const pre = prefix ? `${prefix}_` : "";
    if (
      typeof obj[k] === "object" &&
      obj[k] !== null &&
      !Array.isArray(obj[k])
    ) {
      Object.assign(acc, flattenObject(obj[k], pre + k));
    } else {
      acc[pre + k] = obj[k];
    }
    return acc;
  }, {});
};

// 병합 및 평탄화 로직
const mergedData = allClientList.map((device) => {
  // 이름을 기준으로 commData에서 일치하는 항목 찾기
  const commInfo = luAgentList.find((comm) => comm.name === device.name);

  if (commInfo) {
    // process를 평탄화하고 원래의 장치 객체와 병합
    return {
      ...device, // 장치 객체를 직접 사용
      commSetting: commInfo.commSetting, // commSetting을 그대로 유지
      ...flattenObject(commInfo.process, "process"), // process 평탄화
      status: commInfo.status,
      listLD: commInfo.listLD.map((ld) => ({
        name: ld.name,
        ldNs: ld.ldNs || null, // 선택적 필드
        listLN: ld.listLN.join(", "), // listLN 배열을 쉼표로 구분된 문자열로 변환
      })),
    };
  }

  // 일치하는 commData가 없을 경우 원래 장치를 반환
  return device; // 장치 객체를 직접 반환
});

console.log(mergedData);
